# Generated by Django 3.1.7 on 2021-03-04 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caravan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('tags', models.CharField(blank=True, max_length=511)),
                ('duration', models.CharField(blank=True, max_length=31)),
                ('mood', models.CharField(blank=True, max_length=31)),
                ('age_range', models.CharField(blank=True, max_length=31)),
                ('government', models.CharField(max_length=31)),
                ('private', models.BooleanField()),
                ('blocked_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('parent_caravan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.caravan')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('link', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=511)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=31)),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.caravan')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.hostel')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infavor', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.stop')),
            ],
        ),
    ]
