# Generated by Django 3.1.7 on 2021-03-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='start_date',
        ),
    ]
