# Generated by Django 3.1.7 on 2021-03-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_caravan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravan',
            name='slug',
        ),
    ]
