# Generated by Django 3.1.7 on 2021-03-05 20:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_caravan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=['caravan', 'hostel'], unique=True),
        ),
    ]
