# Generated by Django 3.1.7 on 2021-03-09 20:18

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0006_stop_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='members',
            new_name='attendees',
        ),
        migrations.AddField(
            model_name='caravan',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='_caravan_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stop',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-slug', editable=False, populate_from='caravan', unique=True),
            preserve_default=False,
        ),
    ]
