# Generated by Django 3.1.7 on 2021-03-12 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20210309_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDestination',
            fields=[
                ('hostel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.hostel')),
                ('location', models.CharField(max_length=127)),
            ],
            bases=('feed.hostel',),
        ),
        migrations.CreateModel(
            name='EventDestination',
            fields=[
                ('hostel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.hostel')),
                ('event_name', models.CharField(max_length=31)),
            ],
            bases=('feed.hostel',),
        ),
        migrations.CreateModel(
            name='HostelDestination',
            fields=[
                ('hostel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.hostel')),
                ('rating', models.FloatField()),
            ],
            bases=('feed.hostel',),
        ),
        migrations.RemoveField(
            model_name='caravan',
            name='government',
        ),
        migrations.RemoveField(
            model_name='caravan',
            name='parent_caravan',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='stop',
        ),
        migrations.AddField(
            model_name='caravan',
            name='allow_member_stop_proposals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caravan',
            name='split_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='stop',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='age_range',
            field=models.CharField(choices=[('18-25', '18-23'), ('25-29', '23-29'), ('30-39', '30-39'), ('40-65', '40-65'), ('65+', '65+')], max_length=15),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='duration',
            field=models.CharField(choices=[('event', 'Event'), ('journey', 'Journey'), ('nomadic', 'Nomadic')], max_length=15),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='caravans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='mood',
            field=models.CharField(choices=[('party', 'Party'), ('enjoy', 'Enjoy'), ('explore', 'Explore'), ('volunteer', 'Volunteer'), ('work', 'Work')], max_length=15),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='status',
            field=models.CharField(choices=[('decided', 'Decided'), ('tentative', 'Tentative'), ('proposal', 'Proposal')], max_length=15),
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_vote_multiplier', models.FloatField(default=1)),
                ('legacy_vote_multiplier', models.FloatField(default=1)),
                ('public_ballots', models.BooleanField(default=True)),
                ('caravan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.caravan')),
                ('leaders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=511)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.government')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.forum'),
        ),
        migrations.CreateModel(
            name='StopForum',
            fields=[
                ('forum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.forum')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.stop')),
            ],
            bases=('feed.forum',),
        ),
        migrations.CreateModel(
            name='AddLeaderForum',
            fields=[
                ('forum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.forum')),
                ('new_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('feed.forum',),
        ),
    ]
