# Generated by Django 3.1.7 on 2021-03-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210312_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostel',
            new_name='Destination',
        ),
    ]
