# Generated by Django 3.1.7 on 2021-03-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20210312_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDestination',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.destination')),
                ('location', models.CharField(max_length=127)),
            ],
            bases=('feed.destination',),
        ),
        migrations.CreateModel(
            name='EventDestination',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.destination')),
                ('event_name', models.CharField(max_length=31)),
            ],
            bases=('feed.destination',),
        ),
        migrations.CreateModel(
            name='HostelDestination',
            fields=[
                ('destination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.destination')),
                ('rating', models.FloatField()),
            ],
            bases=('feed.destination',),
        ),
    ]
