# Generated by Django 3.1.7 on 2021-03-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_areadestination_eventdestination_hosteldestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
