# Generated by Django 3.1.7 on 2021-03-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20210315_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='member_vote_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
