# Generated by Django 3.1.7 on 2021-03-15 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0014_government_member_vote_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caravan_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='government',
            name='legacy_vote_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
