# Generated by Django 3.1.7 on 2021-03-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20210329_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='member',
            new_name='user',
        ),
    ]
