# Generated by Django 3.1.7 on 2021-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_auto_20210329_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='leader_checkins',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='government',
            name='legacy_checkins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='government',
            name='legacy_threshold',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='government',
            name='open_checkins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='government',
            name='show_interest_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='government',
            name='vote_against',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caravan',
            name='age_range',
            field=models.CharField(choices=[('18-23', '18-23'), ('23-29', '23-29'), ('30-39', '30-39'), ('40-65', '40-65'), ('65+', '65+'), ('family', 'Family'), ('any', 'All Ages')], max_length=15),
        ),
        migrations.AlterField(
            model_name='government',
            name='leader_vote_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='government',
            name='legacy_vote_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='hosteldestination',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
