# Generated by Django 3.1.7 on 2021-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20210405_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravan',
            name='flexible_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_queue_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='leader_vote_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='government',
            name='member_vote_multiplier',
            field=models.FloatField(default=0),
        ),
    ]
