# Generated by Django 3.1.7 on 2021-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20210405_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='start_date',
        ),
    ]
