# Generated by Django 3.1.7 on 2021-04-05 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_remove_stop_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravan',
            name='split_date',
        ),
        migrations.AddField(
            model_name='caravan',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 4, 5)),
        ),
        migrations.AlterField(
            model_name='stop',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
