# Generated by Django 3.1.7 on 2021-04-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20210405_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopforum',
            name='stop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.stop'),
        ),
    ]
